version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Krika2025**
      MYSQL_DATABASE: krika
      MYSQL_USER: admin
      MYSQL_PASSWORD: Krika2025**
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
